version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=your-database-host
      - DB_PORT=5432
      - DB_DATABASE=your-database-name
      - DB_USERNAME=your-database-username
      - DB_PASSWORD=your-database-password

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: your-database-name
      POSTGRES_USER: your-database-username
      POSTGRES_PASSWORD: your-database-password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
